# Generated by Django 3.0.7 on 2020-08-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0006_auto_20200801_1702"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="url_category",
            field=models.URLField(
                max_length=400, unique=True, verbose_name="Url de la categorie"
            ),
        ),
    ]
