# Generated by Django 3.0.7 on 2020-08-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_auto_20200801_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(to='business.Product'),
        ),
    ]
