# Generated by Django 3.0.7 on 2020-07-20 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0003_auto_20200720_1535"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="purbeurreuser", name="favoris_product",),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_product",
                        to="business.Product",
                    ),
                ),
                (
                    "substitute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_substitute",
                        to="business.Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Favoris",
                "verbose_name_plural": "Favoris",
                "ordering": ["product"],
            },
        ),
        migrations.AddField(
            model_name="purbeurreuser",
            name="favorites",
            field=models.ManyToManyField(to="user.Favorite"),
        ),
    ]
