# Generated by Django 3.0.7 on 2020-07-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_auto_20200720_1816"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purbeurreuser",
            name="favorites",
            field=models.ManyToManyField(to="user.Favorite"),
        ),
    ]
