# Generated by Django 3.0.7 on 2020-08-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_auto_20200720_2301"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purbeurreuser",
            name="favorites",
            field=models.ManyToManyField(to="user.Favorite"),
        ),
    ]
